# Generated by Django 4.2.7 on 2025-10-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('order', 'Order'), ('customer', 'Customer'), ('menu', 'Menu'), ('system', 'System'), ('pos_transaction', 'POS Transaction'), ('menu_view', 'Menu View'), ('cms_update', 'CMS Update'), ('user_login', 'User Login'), ('staff_action', 'Staff Action')], max_length=50),
        ),
    ]
