# Generated by Django 4.2.7 on 2026-03-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_event_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('actor_email', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('order.created', 'Order Created'), ('order.status_changed', 'Order Status Changed'), ('order.payment_confirmed', 'Payment Confirmed'), ('order.cancelled', 'Order Cancelled'), ('staff.invited', 'Staff Invited'), ('staff.activated', 'Staff Activated'), ('staff.deactivated', 'Staff Deactivated'), ('staff.deleted', 'Staff Deleted'), ('staff.role_changed', 'Staff Role Changed'), ('menu.item_created', 'Menu Item Created'), ('menu.item_updated', 'Menu Item Updated'), ('menu.item_deleted', 'Menu Item Deleted'), ('settings.updated', 'Settings Updated'), ('table.created', 'Table Created'), ('table.updated', 'Table Updated'), ('table.deleted', 'Table Deleted')], max_length=100)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(blank=True, max_length=100)),
                ('entity_label', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='analytics_a_action_6ae8f9_idx'), models.Index(fields=['entity_type', 'created_at'], name='analytics_a_entity__2738f1_idx'), models.Index(fields=['actor_email', 'created_at'], name='analytics_a_actor_e_444904_idx')],
            },
        ),
    ]
