# Generated by Django 4.2.7 on 2026-03-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='tenant_schema',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant_schema', 'created_at'], name='analytics_a_tenant__9da5d0_idx'),
        ),
    ]
