# Generated by Django 4.2.7 on 2026-03-11 15:27

from django.db import migrations


def create_default_roles(apps, schema_editor):
    Role = apps.get_model('staff', 'Role')
    Tenant = apps.get_model('tenants', 'Tenant')
    
    # We use connection.schema_name to determine context, but migrations.RunPython 
    # executes within each schema automatically in django-tenants.
    # However, Role has a 'tenant' field we added.
    
    roles_data = [
        {
            'name': 'Owner',
            'description': 'Full system access',
            'permissions': {'*': True}
        },
        {
            'name': 'Manager',
            'description': 'Operations management (limited financial access)',
            'permissions': {
                'dashboard': True,
                'menu': True,
                'orders': True,
                'tables': True,
                'team': True,
                'settings': 'basic',
                'subscriptions': False
            }
        },
        {
            'name': 'Waiter',
            'description': 'POS access and order creation',
            'permissions': {
                'pos': True,
                'orders': 'create'
            }
        }
    ]
    
    # Note: In django-tenants, this migration runs once per schema.
    # We need to find the current tenant for the schema.
    from django.db import connection
    schema_name = connection.schema_name
    
    if schema_name == 'public':
        return # Skip public schema if preferred, or seed base roles there
        
    try:
        tenant = Tenant.objects.get(schema_name=schema_name)
    except Tenant.DoesNotExist:
        return

    for role_info in roles_data:
        Role.objects.update_or_create(
            tenant=tenant,
            name=role_info['name'],
            defaults={
                'description': role_info['description'],
                'permissions': role_info['permissions']
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_role_tenant_staffmember_tenant'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_roles),
    ]
