# Generated by Django 4.2.7 on 2025-09-28 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['sort_order']},
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='includes_menu',
            new_name='has_advanced_analytics',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_staff',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_tables',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='price_ngn',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='price_usd',
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='paystack_access_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_basic_analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_custom_integrations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_multi_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='includes_digital_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='starter', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='support_level',
            field=models.CharField(choices=[('email', 'Email Support'), ('priority', 'Priority Support'), ('phone_24_7', '24/7 Phone Support')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='GHS', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_menu_items',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trialing', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('unpaid', 'Unpaid')], default='trialing', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant'),
        ),
    ]
