# Generated by Django 4.2.7 on 2025-10-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_plan_allows_menu_images_alter_plan_plan_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_to_ghs', models.DecimalField(decimal_places=2, default=12.68, max_digits=10)),
                ('usd_to_ngn', models.DecimalField(decimal_places=2, default=1484.9, max_digits=10)),
                ('use_api', models.BooleanField(default=True, help_text='Use live API rates when available')),
                ('api_key', models.CharField(default='28f53f97e95df6d8f7ab87ec', help_text='ExchangeRate-API key', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exchange Rate Settings',
                'verbose_name_plural': 'Exchange Rate Settings',
            },
        ),
        migrations.RemoveField(
            model_name='plan',
            name='price_ghs',
        ),
        migrations.AddField(
            model_name='plan',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
