# Generated by Django 4.2.7 on 2026-03-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('dine_in', 'Dine-in'), ('pickup', 'Pick-up'), ('delivery', 'Delivery')], default='dine_in', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
