# Generated by Django 4.2.7 on 2026-03-14 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_address_tenant_logo_tenant_phone_and_more'),
        ('orders', '0004_order_payment_status_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_stale_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.order')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tenants.tenant')),
            ],
        ),
    ]
