# Generated by Django 4.2.7 on 2026-03-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_is_stale_notified_orderreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='processed_by_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
