# Generated by Django 4.2.7 on 2026-03-28 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_processed_by_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreview',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.order'),
        ),
    ]
