# Generated by Django 4.2.7 on 2026-03-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='icon',
            field=models.CharField(default='Settings', max_length=50),
        ),
        migrations.AddField(
            model_name='tool',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tool',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
